#!/usr/bin/env python3
"""Copy `core/jobhunt.py` into every skill that ships a script.

Skills are installed one at a time. A skill that imported from a sibling would
work in this repo and break the moment somebody installs it on its own, so each
one carries its own copy of the library and none of them import across.

That duplication is the design, not an oversight - but duplication that drifts
is worse than either choice, so this is the only thing allowed to write those
copies and `test_skills.py` fails if any of them differs from the source.

    python tools/sync.py           write the copies
    python tools/sync.py --check   exit 1 if any is out of date
"""

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "core" / "jobhunt.py"
SKILLS = ROOT / "plugins" / "jobhunt" / "skills"

HEADER = (
    "# Generated by tools/sync.py from core/jobhunt.py - do not edit here.\n"
    "# Every skill carries its own copy so it works installed on its own.\n"
)


def copies():
    """Every skill directory that ships a script, and so needs the library."""
    for skill in sorted(SKILLS.iterdir()) if SKILLS.exists() else []:
        if skill.is_dir() and any(skill.glob("*.py")):
            yield skill / "lib" / "jobhunt.py"


def wanted():
    return HEADER + SOURCE.read_text(encoding="utf-8")


def main(argv):
    check = "--check" in argv
    body = wanted()
    digest = hashlib.sha256(body.encode()).hexdigest()[:12]
    stale = []

    for target in copies():
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current == body:
            continue
        stale.append(target.relative_to(ROOT))
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")

    total = len(list(copies()))
    if check and stale:
        print(f"out of date ({len(stale)} of {total}):", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("\nRun: python tools/sync.py", file=sys.stderr)
        return 1
    print(f"{'checked' if check else 'wrote'} {total} copies of jobhunt.py [{digest}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
